### ISSUE TITLE
Console output not working

### ISSUE THREAD

**Issue by dietercoopman** [lsrur/inspector#12]
Hello,

your inspector looks very promising , but if i test it and want to use it i see the javascript code is added to my DOM. But i get a javascript error. I've tested with chrome / firefox ( telling me 'Invalid or unexpected token' , if i test in safari then i get 'unexpected end of file' 

![javascript](https://cloud.githubusercontent.com/assets/4672752/17580638/7d0e5276-5fa0-11e6-9111-35378c3bb2d6.png)
<img width="438" alt="error" src="https://cloud.githubusercontent.com/assets/4672752/17580637/7d0a1990-5fa0-11e6-9af6-d9c518ece2ce.png">

**Comment by dietercoopman** [comment]
I've got it working if i use a simple view , i'll try to find out when it occurs and give you some feedback when the problem occurs

**Comment by dietercoopman** [comment]
Hellow , i found the problem ,  i am using a view composer for my menu.  When i pass an empty array to my view everything works fine, i see the laravel inspector in my console.  But when i pass menu objects then i get the error mentioned above

with this in my view composer it works :
```
    public function compose(View $view)
    {
        $menus = [];
        $view->with(compact('menus'));
    }
```

with this it doesn't work  ( passing eloquent models )

```
    public function compose(View $view)
    {
        $menus = Menu::all();
        $view->with(compact('menus'));
    }
```

**Comment by lsrur** [comment]
Hi
What webserver stack are you using? Is it on Windows?  
thanks for your time improving this package.

**Comment by dietercoopman** [comment]
Hello

It is on debian => Debian 3.2.73-2+deb7u2 i686 , php 5.6.17-1, mysql 5.5.46

**Comment by lsrur** [comment]
Could you send me please the entire generated html? ("view source" from the browser")

**Comment by dietercoopman** [comment]
i've sent it via mail

**Comment by lsrur** [comment]
Is that the html of the faulty behavior?

**Comment by dietercoopman** [comment]
yes it is

**Comment by dietercoopman** [comment]
hmmm , if i save the html to a .html and open it with a browser i see the laravel inspector ... strange

**Comment by lsrur** [comment]
Yes, me too. Did you copy & paste?  Try "save" from the browser... There may be an EOL byte  bothering the file..

**Comment by dietercoopman** [comment]
i copy pasted indeed , saveing it gives me the error to , i've send you a test url

**Comment by lsrur** [comment]
Yes! I can see it now... I go bug hunting ...

**Comment by dietercoopman** [comment]
thx for the bugfix !!
