### ISSUE TITLE
Inspector catching error in request, is it wanted behavior?

### ISSUE THREAD

**Issue by jpmurray** [lsrur/inspector#4]
Hi again!

I just realized that, when using requests to make validation, if said validation fails, Inspecter catches the error rather than letting it go so the frontend can display the validation error.

Is it intended behavior? This is what get's thrown on validation errors.

<img width="1417" alt="screen shot 2016-08-05 at 11 05 24" src="https://cloud.githubusercontent.com/assets/1550428/17440892/93fbe744-5afc-11e6-9baf-19166008948c.png">

**Comment by lsrur** [comment]
Hi Jean-Philippe,
No, it is not, let me think for a while on how to handle this.

**Comment by lsrur** [comment]
Hi Jean-Philippe,
I just pushed a new version with both issues addressed, can you please test it?

**Comment by jpmurray** [comment]
I'm off for a meeting, I'll be testing in the coming hours! ;-)

**Comment by jpmurray** [comment]
That seems to have done the trick! Thank you!

Nice package you have there, I really love it!
