### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token when querying models

### ISSUE THREAD

**Issue by rsdev000** [lsrur/inspector#7]
Hi

Created a dummy laravel app (5.2.41), added a model and get this error.
Tested in windows with latest php 7, latest chrome, latest firefox without extras, firefox dev edition.

Routes.php
```php
Route::get('/', function () {
    $data = \App\Models\Test::all();

    return view('welcome');
});
```
The error in the console and the response (see attached files)

![error_1](https://cloud.githubusercontent.com/assets/9252353/17458570/0480d19e-5c0d-11e6-9813-de03c0fc081b.png)
![error_2](https://cloud.githubusercontent.com/assets/9252353/17458571/06d3b510-5c0d-11e6-9148-0d778749c962.png)

[response.txt](https://github.com/lsrur/inspector/files/405138/response.txt)

Cheers

**Comment by lsrur** [comment]
Hi
I have a similar report under windows and open-server (open-server.ru) stack. I'm not sure if it's a problem with Windows or the web server software. I just checked this package under Laravel Valet (mac) and Homestead (linux). I'm going to setup a windows vm to check it out. Do you use xampp, wamp, mamp for windows...?

**Comment by lsrur** [comment]
It's fixed, please check it out.

2016-08-06 15:40 GMT-03:00 rsdev000 <notifications@github.com>:

**Comment by rsdev000** [comment]
:) Version 1.0.2 is working as expected. 

Thanks for fixing this quickly. I don't use any *ampp solution. My setup is like a linux setup. It allows to upgrade/downgrade each piece of the stack in a matter of minutes or less.

Cheers
