### ISSUE TITLE
Production mode and Blade

### ISSUE THREAD

**Issue by blackfyre** [lsrur/inspector#9]
Hi! :smile: 

We've come across a little bug :wink: 
The application is in production and debug mode is set to `false`, but due to a call to the logger in one of our template files we get the following error:

```
production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function log() on null in /home/forge/project-folder/storage/framework/views/018a7947e9a28700eda1911e35edd3856a9e8db5.php:10
```

The package has been installed and works correctly if debug mode is on, but it's not a production safe solution. I hope this helps.

**Comment by lsrur** [comment]
Thank you blackfyre, I'll check it out ASAP.

**Comment by lsrur** [comment]
I think it's fixed. Please test the new version.

**Comment by blackfyre** [comment]
Hi!

It looks like it's fixed with the latest release!
